= geOrchestra Gateway
:toc:
:toc-placement!:

**geOrchestra Gateway** is a https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/[Spring Cloud Gateway]
service acting as the single entry point to back-end geOrchestra applications, handling authentication and authorization
on their behalf.


toc::[]


== Introduction

The following diagram provides a high-level overview of how Spring Cloud Gateway works:

[source,mermaid]
----
flowchart LR
    subgraph gateway [Gateway]
    direction TB
        handler_mapping-->web_handler(Web Handler)
        web_handler-->filter_chain(Filter Chain)
        filter_chain-->proxy_filter(Proxy Filter)
    end
    client(Web Client)-->handler_mapping(Handler Mapping)
    proxy_filter-->proxied_service(Proxied Services)
----

Clients make requests to the Gateway. If the Gateway Handler Mapping determines that a request
matches a route, it is sent to the Gateway Web Handler.
This handler runs the request through a filter chain that is specific to the request.
Filters can run logic both before and after the proxy request is sent. All “pre” filter
logic is executed. Then the proxy request is made. After the proxy request is made,
the “post” filter logic is run.

[source,mermaid]
----
flowchart TB
    subgraph filters [Gateway Filter chain]
      direction TB
      subgraph geor_filters [geOrchestra Filter chain]
          remove_sec_headers(RemoveSecurityHeadersGatewayFilter)-->resolve_target
          resolve_target(ResolveTargetGlobalFilter)-->resolve_user(ResolveGeorchestraUserGlobalFilter)
          resolve_user-->add_sec_headers(AddSecHeadersGatewayFilter)
      end
        token_relay(TokenRelayGatewayFilter)-->route_to_request
        route_to_request(RouteToRequestUrlFilter)-->remove_sec_headers
        add_sec_headers-->proxy_filter(Proxy Filter)
    end
    proxy_filter-->proxied
----

Refer to xref:custom-filters.adoc[geOrchestra Gateway custom filters] for more information.

== Data directory property sources

Routes and other relevant configuration properties are loaded from geOrchestra "data directory"'s
`default.properties` and `gateway/gateway.yaml`.

The location of the data directory is picked up from the `georchestra.datadir` environment property,
and the additional property sources by means of spring-boot's 
`spring.config.import` environment property, like in:
`spring.config.import: ${georchestra.datadir}/default.properties,${georchestra.datadir}/gateway/gateway.yaml`.

== Advanced Topics

=== Logging Configuration

For detailed information about logging capabilities, configuration options, and best practices, refer to the xref:logging.adoc[Logging Configuration] guide.

