= geOrchestra Gateway custom filters
:toc:
:toc-placement!:

toc::[]


== Global filters

https://docs.spring.io/spring-cloud-gateway/reference/spring-cloud-gateway/global-filters.html[Gobal filters]
are special filters that are conditionally applied to all routes.

The **geOrchestra Gateway** provides the following global filters

=== ResolveTargetGlobalFilter

Resolves the `GeorchestraTargetConfig` for the request's matched `Route` and stores as a `ServerWebExchange` attribute.
`GeorchestraTargetConfig` contains the target service's security header requirements and the set of role-based access
rules to different service endpoints.


=== ResolveGeorchestraUserGlobalFilter

Resolves the `GeorchestraUser` from the request's `Authentication` so it can be retrieved down the chain during a server
web exchange filter chain execution.

The resolved per-request `GeorchestraUser` object can then, for example, be used to append the necessary `sec-*` headers that relate
to user information to proxied http requests.


== GatewayFilter Factories

Route filters allow the modification of the incoming HTTP request or outgoing HTTP response in some manner.
Route filters are scoped to a particular route, or can be applied to all routes when used in the
`spring.cloud.gateway.default-filters` configuration.

Spring Cloud Gateway comes with a number of
https://cloud.spring.io/spring-cloud-gateway/multi/multi__gatewayfilter_factories.html[GatewayFilter Factories]

The **geOrchestra Gateway** provides the following gateway filters:


=== LoginParamRedirectGatewayFilterFactory

Redirects idempotent requests (`GET`, `HEAD`, `OPTIONS`, `TRACE`) that contains a `login` query
parameter to the `/login` endpoint, as long as the request is not already authenticated.

That is, for example, a `GET /geonetwork/?login` request will be forced to return a `302` redirect
HTTP status with a `Location: /login` response header, if the request was not authenticated already,
and will proceed normally otherwise.

Usage:

As a default filter, to be applied to all routes:
----
spring:
  cloud:
    gateway:
      default-filters:
      - LoginParamRedirect
----

For a specific route:
----
spring:
  cloud:
    gateway:
      routes:
      - id: geonetwork
        uri: http://geonetwork:8080
        predicates:
        - path: /geonetwork/**
        filters:
        - LoginParamRedirect
----

=== RemoveSecurityHeadersGatewayFilter

Removes any incoming `sec-\*` request header to prevent impersonation. Valid `sec-*` headers ought to be
computed by the filter chain and appended to proxied requests. This filter also removes the
`Authorization: basic [...]` http headers, which is meant to authenticate geOrchestra users and
should not be sent to proxified webapps.

Technically, this filter is an instance of the `RemoveHeadersGatewayFilter` (see next section)
instanciated with the following regex:

```
"(?i)(sec-.*|Authorization)"
```

=== RemoveHeadersGatewayFilter

This filter is a more generic version of the previous one, which allows to pass a custom regular
expression as parameter.

Considering you want to strip Basic-authentication http headers, but keep the bearer-related ones
proxified to underlying webapps, one could use the following configuration:

```
spring:
  cloud:
    gateway:
      routes:
      - id: proxified-service
        uri: http://proxified-service:8080
        predicates:
        - Path=/proxified-service/**
        filters:
        # Strip basic authentication headers but keep bearer ones
        - RemoveHeaders=(?i)^(sec-.*|Authorization:(?!\s*Bearer\s*$))
```

=== AddSecHeadersGatewayFilter

Adds all necessary `sec-*` request  headers to proxied requests. Delegates to the `HeaderContributor` extension
point to prepare the exact set of headers to append to each request.

Implementations can use the resolved `GeorchestraTargetConfig` and `GeorchestraUser` to compute 
the target service required header names and values.

[source,mermaid]
----
classDiagram
  direction LR
  HeaderContributor <|-- GeorchestraUserHeadersContributor
  HeaderContributor <|-- GeorchestraOrganizationHeadersContributor
  HeaderContributor <|-- JsonPayloadHeadersContributor
  HeaderContributor <|-- SecProxyHeaderContributor
  class HeaderContributor{
    <<interface>>
    prepare(ServerWebExchange exchange) Consumer~HttpHeaders~
  }
----


=== RouteProfileGatewayFilterFactory

TODO: document

=== StripBasePathGatewayFilterFactory

TODO: document
